# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: libapp-sc
  namespace: nani
type: Opaque
data:
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: cm9vdA==
  DB_NAME: ZGlnaXRhbF9saWJyYXJ5


---
# ConfigMaps
apiVersion: v1
kind: ConfigMap
metadata:
  name: libapp-config
  namespace: nani
data:
  DATABASE_HOST: "db"
  DATABASE_PORT: "3306"
