
#15. Resource Quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: libapp-quota
  namespace: nani
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"            # Max CPU limits across all pods
    limits.memory: 4Gi         # Max memory limits across all pods
    pods: "24"
