#15. Resource Quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: libapp-quota
  namespace: nani
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"            # Max CPU limits across all pods
    limits.memory: 2Gi         # Max memory limits across all pods
    pods: "7"
