#------------------
#Statefulset
#----------------
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: nani
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: nareshujjineni/flm0307:dbimage
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: libapp-config
            - secretRef:
                name: libapp-sc
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html/
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

#---------------
#Auth Deployment
#---------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: nani
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: nareshujjineni/flm0307:authimage
          ports:
            - containerPort: 5001
          env:
            - name: confcon
              valueFrom:
                configMapKeyRef:
                  name: libapp-config
                  key: NameCon
            - name: confipl2
              valueFrom:
                configMapKeyRef:
                  name: libapp-config
                  key: IPL5
            - name: secrcon
              valueFrom:
                secretKeyRef:
                  name: libapp-sc
                  key: NameSC
            - name: secripl
              valueFrom:
                secretKeyRef:
                  name: libapp-sc
                  key: IPL2
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
#----------
#Book
#----------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
  namespace: nani
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book
          image: nareshujjineni/flm0307:bookimage
          ports:
            - containerPort: 5002
          resources:
            requests:
              cpu: "50m"       # Minimum guaranteed CPU
              memory: "128Mi"   # Minimum guaranteed memory
            limits:
              cpu: "100m"       # Maximum CPU allowed
              memory: "256Mi"   # Maximum memory allowed
#----------
#Borrow
#----------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrow
  namespace: nani
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borrow
  template:
    metadata:
      labels:
        app: borrow
    spec:
      containers:
        - name: borrow
          image: nareshujjineni/flm0307:borrowimage
          ports:
            - containerPort: 5003
          resources:
            requests:
              cpu: "50m"       # Minimum guaranteed CPU
              memory: "128Mi"   # Minimum guaranteed memory
            limits:
              cpu: "100m"       # Maximum CPU allowed
              memory: "256Mi"   # Maximum memory allowed

#-------
#Frontend
#--------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nani
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nareshujjineni/flm0307:appimage1
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: libapp-config
            - secretRef:
                name: libapp-sc
          livenessProbe:
            exec:
              command:
                - cat
                - /app/app.py
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          resources:
            requests:
              cpu: "50m"       # Minimum guaranteed CPU
              memory: "128Mi"   # Minimum guaranteed memory
            limits:
              cpu: "100m"       # Maximum CPU allowed
              memory: "256Mi"   # Maximum memory allowed

# ---------------------------------------------
# Services
# ---------------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: nani
spec:
  selector:
    app: db
  ports:
    - port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: nani
spec:
  selector:
    app: auth
  ports:
    - port: 5001
      targetPort: 5001

---

apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: nani
spec:
  selector:
    app: book
  ports:
    - port: 5002
      targetPort: 5002

---

apiVersion: v1
kind: Service
metadata:
  name: borrow-service
  namespace: nani
spec:
  selector:
    app: borrow
  ports:
    - port: 5003
      targetPort: 5003

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: nani
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 5000
