apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: flm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: nareshujjineni/flm0307:authimage
          ports:
            - containerPort: 5001
